### PR TITLE
feat: support databend

### PR DESCRIPTION
**Pull request by hantmac**
Related issue: https://github.com/ScalefreeCOM/datavault4dbt/issues/131

### CODE REVIEW

**Comment by hantmac** [comment]
HI @tkirschke, would you like to help me review this pr?

**Comment by tkirschke** [comment]
> HI @tkirschke, would you like to help me review this pr?

Hi @hantmac ,

Thanks for your PR! Looking forward to review it as soon as I have some time for it. Will have to setup a Databend test instance first, and a dbt project connected to it. 

Will let you know when I was able to review!

**Comment by hantmac** [comment]
@tkirschke Thanks for your reply! 

First of all, The databend cloud https://app.databend.com has a free using plan, you can apply it and use the databend cloud instance directly. 
Secondly,  databend has the dbt adapter https://github.com/databendcloud/dbt-databend, we can use it set up a dbt project and connect to databend.

**Comment by tkirschke** [comment]
Closed because Support of Databend is not planned for the near future.

**Pull request closed without merging**
