### PR TITLE
140 optionality for nh link foreign hashkeys

### PR DESCRIPTION
**Pull request by filcov**
# Description

Please include a summary of the changes and the related issue and context.

Fixes #(issue)
Lack of optionality for foreign keys in non-historized links
## Type of change
added such feature by modifying models related to nh_links
Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?
I tested the new feature by running the datavault4dbt-ci-cd branch [140-optional-FK](https://github.com/ScalefreeCOM/datavault4dbt-ci-cd/tree/refs/heads/140-optional-FK) using the dbt test action. This was done in conjunction with the branch from the automatic tests repository: [optional-foreignHK-for-NHLink](https://github.com/ScalefreeCOM/datavault4dbt-automatic-tests/tree/optional-foreignHK-for-NHLink) and the corresponding datavault4dbt branch [140-Optionality-for-NHLink-foreign-hashkeys](https://github.com/ScalefreeCOM/datavault4dbt/tree/140-Optionality-for-NHLink-foreign-hashkeys).

Test Setup:
Added two new test cases: nh_link_05 and nh_link_06 models with corresponding tests in the nh_link_tests.yml file. These new models are designed to exclude foreign keys, ensuring the functionality of the new optional foreign key feature.
Steps to Reproduce:
Run the dbt test action on the datavault4dbt-ci-cd branch [140-optional-FK](https://github.com/ScalefreeCOM/datavault4dbt-ci-cd/tree/refs/heads/140-optional-FK) selecting the [140-Optionality-for-NHLink-foreign-hashkeys](https://github.com/ScalefreeCOM/datavault4dbt/tree/140-Optionality-for-NHLink-foreign-hashkeys) as datavault4dbt package 
Verify that the tests nh_link_05 and nh_link_06 successfully validate the behavior without foreign keys. (check also other nh_links )
These steps ensure that the new optional foreign key functionality works as expected.
if they don't work as expected:
Clone the datavault4dbt-ci-cd branch 140-optional-FK. (to view it)
Clone the automatic tests repository with the optional-foreignHK-for-NHLink branch. ( to view it)
And the corresponding 140-Optionality-for-NHLink-foreign-hashkeys as datavault4dbt package 
and modify them as needed

**Test Configuration**:
* datavault4dbt-Version: 1.41
* dbt-Version: core, version number_1.9.0b2
* dbt-adapter-Version: based on datavault4dbt-ci-cd branch [140-optional-FK](https://github.com/ScalefreeCOM/datavault4dbt-ci-cd/tree/refs/heads/140-optional-FK)

# Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation or included information that needs updates (e.g. in the Wiki)

### CODE REVIEW

**Comment by tkirschke** [comment]
Please Add Databricks & Oracle

**Comment by filcov** [comment]
@tkirschke I added the modifications to Oracle and Databricks. Then I successfully tested with datavautl4dbt-ic-cd dbt test. 

> Please Add Databricks & Oracle

**Review by tkirschke — APPROVED** [review]

**Comment by tkirschke** [comment]
Hi @filcov , 

Just started the pipeline! Could you please already adjust the Webiste documentation regarding optionality of Foreign Hashkeys?

**Comment by filcov** [comment]
> Hi @filcov ,
> 
> Just started the pipeline! Could you please already adjust the Webiste documentation regarding optionality of Foreign Hashkeys?

Done!

**Pull request merged**
