### PR TITLE
Oracle support

### PR DESCRIPTION
**Pull request by universe-designer**
Added Oracle connectivity for

- hubs
- links
- satellites
- hub record tracking satellites
- link record tracking satellites
- pits
- multi active satellites

Todo

- non historized links
- non historized satellites
- dynamic hash function selection. Currently only SHA1 support

### CODE REVIEW

**Comment by universe-designer** [comment]
Added PIT tables for oracle

**Comment by universe-designer** [comment]
Added PIT tables for oracle

**Comment by universe-designer** [comment]
Added multi active satellites for Oracle

**Comment by universe-designer** [comment]
fixed bug for incremental multi active satellite

**Comment by universe-designer** [comment]
Removes the "as" in prejoined_columns to work with oracle

**Review by kgruenhagen — APPROVED** [review]
First review done. Advanced testing coming up.

**Pull request merged**
